myrecipe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from homeview import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home_view'),
    url(r'^admin/', admin.site.urls),
    url(r'^recipe/', include('recipe.urls', namespace='recipe')),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logout.html'}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipe/urls.py
from django.conf.urls import url

from . import step_view, recipes_view

urlpatterns = [
    url(r'^$', recipes_view.list_recipe, name='List_Recipe'),
    url(r'^create/$', recipes_view.create_recipe, name='Create_Recipe'),
    url(r'^(?P<recipe_id>\d+)/delete/$', recipes_view.delete_recipe, name='Delete_Recipe'),
    url(r'^(?P<recipe_id>\d+)/edit/$', recipes_view.update_recipe, name='Update_Recipe'),
    url(r'^(?P<recipe_id>\d+)/$', recipes_view.detail_recipe, name='Detail_Recipe'),
    url(r'^(?P<recipe_id>\d+)/createstep/$', step_view.create_step, name='Create_Step'),
    url(r'^(?P<step_id>\d+)/editstep/$', step_view.update_step, name='Update_Step'),
    url(r'^(?P<step_id>\d+)/deletestep/$', step_view.delete_step, name='Delete_Step'),
]

#<a href="{% url '' id=obj.id %}"></a>

recipe/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse


class Recipes(models.Model):
    recipe_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    owner = models.CharField(max_length=50, null=False, blank=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    # step = models.ManyToManyField(Steps)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("recipe:Detail_Recipe", kwargs={'recipe_id': self.recipe_id})

    class Meta:
        ordering = ['-timestamp', '-updated']


class Steps(models.Model):
    step_id = models.AutoField(primary_key=True)
    number = models.IntegerField(default=1)
    description = models.TextField(null=False, blank=False)
    owner = models.CharField(max_length=50, null=False, blank=False)
    #recipe = models.ManyToManyField(Recipes)
    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE)

    def __unicode__(self):
        return '{0}'.format(self.step_id)

recipe/forms.py
from django import forms
from .models import Recipes, Steps


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipes
        fields = [
            "title",
            "description"
        ]


class StepsForm(forms.ModelForm):
    class Meta:
        model = Steps
        fields = [
            "number",
            "description",
        ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% include 'head.html' %}
    <body>
        {% include 'navbar.html' %}
        <div class="col-sm-10 col-sm-offset-1">
            {% block pageContent %} {% endblock %}
        </div>

        {% include 'footer.html' %}

        {% block customJsFiles %}{% endblock %}

        <script>
            $(document).ready(function () {
                $.ajaxSetup({cache: false});
                {% block customJs %}{% endblock %}
            });
        </script>
    </body>
</html>

templates/footer.html
{% load staticfiles %}
<footer class="footer">
    <div class="container">
        <p class="text-center text-muted">
            <a href="{#{% url 'recipe:index' %} #}" class="text-muted">Recipe</a>
        </p>
        <p class="copyright" align="center">
            © <span id="year">2016</span> MyRecipe. All Rights Reserved
        </p>
    </div>
</footer>

templates/head.html
{% load staticfiles %}
<head>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{% block pageDescription %}{% endblock %}">
<title>{% block pageTitle %}{% endblock %}</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<link rel=stylesheet type=text/css href="{% static 'css/base.css' %}">
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</head>

templates/login.html
{% extends 'base.html' %}
{% block pageContent %}
    <div class="container-fluid">
        <div class="col-md-4" style="margin-right:auto; margin-left:auto; float: none">
            <div class="panel panel-default">
                <div style="margin:25px;" >
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/logout.html
{% extends "base.html" %}

{% block content %}

Logged out!

{% endblock %}

templates/myrecipe/detail_recipe.html
{% extends 'base.html' %}

{% block pageContent %}
    <!-- page content -->
    {% include 'myrecipe/message.html' %}


    <div class="row">

        <div class="col-sm-12" style="border: thin solid black">

                <h3 class="text-primary">{{ title | title }}
                    <small style="margin-top: 5px">  {{ recipe.timestamp }}</small></h3>

                <ul><h4 class="text-primary">Recipe Description</h4>
                    <ul>{{ recipe.description|linebreaks }}</ul>
                </ul>


                <ul>
                    <h4 class="text-primary">Steps to follow</h4>
                    {% for step in steps_obj %}
                        <li class="col-sm-10 col-sm-offset-1">{{ step.description }}
                        {% if recipe.owner == user.username %}
                                <a href="{% url 'recipe:Update_Step' step_id=step.step_id %}?next={% url 'recipe:List_Recipe' %}" class="btn-space">
                                    <span><i class="glyphicon glyphicon-pencil fa-fw"></i></span></a>

                                <a href="{% url 'recipe:Delete_Step' step_id=step.step_id %}?next={% url 'recipe:List_Recipe' %}" class="btn-space">
                                    <span style="color:red"><i class="glyphicon glyphicon-trash fa-fw"></i></span></a>
                        {% endif %}
                        </li>
                    {% endfor %}
                </ul>
                <blockquote class="col-sm-2 col-sm-offset-10"><small class="text-primary">{{ recipe.owner | title}}</small></blockquote>
        </div>
    </div>

{% endblock %}

{% block customJsFiles %}
    <!-- Add all your custom js files here.... -->
{% endblock %}

{% block customJs %}

{% endblock %}

templates/myrecipe/index.html
{% extends 'base.html' %}

{% block pageContent %}
    <!-- page content -->
    <h1 class="text-primary">Welcome to Awesome Recipes!!!</h1>
    {% include 'myrecipe/recipe_content.html' %}

{% endblock %}

{% block customJsFiles %}
    <!-- Add all your custom js files here.... -->
{% endblock %}

templates/myrecipe/message.html
<div class="col-sm-9 col-sm-offset-3">
    <div class="Captain">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags %}
                    {% if message.tags == 'success' %}
                        <div style="color: green">{{ message }}</div>
                    {% else %}
                        <div style="color: red">{{ message }}</div>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
    </div>
</div>

templates/myrecipe/recipe.html
{% extends 'base.html' %}

{% block pageContent %}
    <!-- page content -->

    <h1 class="text-primary">{{ user.username | title }} Recipe page</h1>
    {% include 'myrecipe/message.html' %}
    {% include 'myrecipe/recipe_content.html' %}

{% endblock %}

{% block customJsFiles %}
    <!-- Add all your custom js files here.... -->
{% endblock %}

templates/myrecipe/recipe_content.html
{% load static %}
<div class='btn-toolbar'>
    {% if page_id == "recipe"  %}
        <a href="{% url 'recipe:Create_Recipe' %}" class="btn pull-right btn-primary" role="button">Create Recipe</a>
    {% endif %}

    <form method="GET" action="">
        <input type="text" name="query" placeholder="Search Recipe" value="{{ request.GET.query}}" class="pull-right"/>
    </form>
</div>

<div class="row">
    {% for obj in recipes_list %}

        <div class="col-sm-4">
            <div class="thumbnail">
                <div class="captain">
                    {% if page_id == "recipe" %}

                        <div>
                            <a href="{% url 'recipe:Update_Recipe' recipe_id=obj.recipe_id %}?next={% url 'recipe:List_Recipe' %}" class=" pull-right btn-space">
                                <span><i class="glyphicon glyphicon-pencil fa-fw"></i></span></a>

                            <a href="{% url 'recipe:Delete_Recipe' recipe_id=obj.recipe_id %}?next={% url 'recipe:List_Recipe' %}" class="pull-right btn-space">
                                <span style="color:red"><i class="glyphicon glyphicon-trash fa-fw"></i></span></a>
                        </div>

                    {% endif %}

                    <h3 class="no-margin"><a href="{% url 'recipe:Detail_Recipe' recipe_id=obj.recipe_id %}" style="color: green">{{ obj.title | title }}</a></h3>
                        <h4 class="no-margin"><small>{{ obj.owner | title}},  {{ obj.timestamp }}</small></h4>
                    <p>{{ obj.description|linebreaks|truncatewords:10 }}</p>

                    <div class='btn-toolbar'>
                        <a href="{% url 'recipe:Detail_Recipe' recipe_id=obj.recipe_id %}" class="btn pull-right btn-primary" role="button">View</a>
                        {% if page_id == "recipe" %}
                            <a href="{% url 'recipe:Create_Step' recipe_id=obj.recipe_id %}" class="btn pull-right btn-primary" role="button">Add Step</a>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>

    {% endfor %}

    <div class="pagination col-sm-12 Captain">
        <span class="step-links pull-right">
            {% if recipes_list.has_previous %}
                <a href="?page={{ recipes_list.previous_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ recipes_list.number }} of {{ recipes_list.paginator.num_pages }}.
            </span>

            {% if recipes_list.has_next %}
                <a href="?page={{ recipes_list.next_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">next</a>
            {% endif %}
        </span>
    </div>
</div>

templates/myrecipe/recipe_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block pageContent %}

    <div class="col-sm-6 col-sm-offset-3">
        <h1>Recipe Form</h1>

        <form method="POST" action="">

            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" class="btn btn-primary" value="Create Recipe">

        </form>
    </div>


{% endblock %}

{% block customJsFiles %}
    <!-- Add all your custom js files here.... -->
{% endblock %}

templates/myrecipe/step_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block pageContent %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1>Recipe Step Form</h1>

        <form method="POST" action="">

            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" class="btn btn-primary" value="Create Step">

        </form>
    </div>

{% endblock %}

{% block customJsFiles %}
    <!-- Add all your custom js files here.... -->
{% endblock %}

templates/navbar.html
<!-- Static navbar -->{% load staticfiles %}
<div class="navbar navbar-inverse navbar-static-top" style="margin-bottom: 10px;" role="navigation">

    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">My Recipes</a>
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="navbar-collapse collapse">

            <!-- Left Nav bar tabs-->
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'recipe:List_Recipe' %}">My Recipes</a></li>
                {% endif %}
            </ul>

            <!-- Right Nav bar tabs-->
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="#"><span class="glyphicon glyphicon-user"></span>{{ user.username }}</a></li>
                    <li><a href="{% url 'logout' %}?next=/"><i class="glyphicon glyphicon-log-out"></i> Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={% url 'recipe:List_Recipe' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>